version: '2'
services:
    api:
        build: .
        container_name: spaghetti_api
        restart: unless-stopped
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - "/var/spaghetti:/data"
        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}
    db:
        image: mongo
        container_name: spaghetti_db
        restart: unless-stopped
