version: "3.5"

networks:
    spaghetti:
        external: false

services:
    api:
        build: .
        container_name: spaghetti_api
        restart: unless-stopped
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - "/var/spaghetti/api:/data"
        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}
        networks:
            - spaghetti
    db:
        image: mongo
        container_name: spaghetti_db
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - /var/spaghetti/db:/data/db
        networks:
            - spaghetti
